package:
  name: "towerpy"
  version: "1.0.1"

source:
  git_rev: v1.0.1
  git_url: https://github.com/uobwatergroup/towerpy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - matplotlib >=3.5.2
    - scipy
    - cartopy
    - netcdf4

about:
  home: https://doi.org/10.1016/j.envsoft.2023.105746
  license: GPLv3
  license_familY: GNU General Public License
  license_file: LICENSE
  summary: "Towerpy: an open-source toolbox for processing polarimetric radar data"
  doc_url: https://doi.org/10.1016/j.envsoft.2023.105746

extra:
  recipe-maintainers:
    - towerpy
    - enchiladaszen

